### ISSUE TITLE
Issue with installing requirements.txt 

### ISSUE THREAD

**Issue by edsun123** [aqeelanwar/DRLwithTL_real#17]
Failed to build or setup av. There is version 8.0.2 but the requirements.txt specifying av == 0.4.0 

Building wheels for collected packages: av
  Building wheel for av (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/user/anaconda3/envs/my_env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dco3y311/av/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dco3y311/av/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-1aag3fl5
       cwd: /tmp/pip-install-dco3y311/av/
  Complete output (59 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/av
  copying av/__init__.py -> build/lib.linux-x86_64-3.6/av
  copying av/__main__.py -> build/lib.linux-x86_64-3.6/av
  creating build/lib.linux-x86_64-3.6/av/video
  copying av/video/__init__.py -> build/lib.linux-x86_64-3.6/av/video
  creating build/lib.linux-x86_64-3.6/av/codec
  copying av/codec/__init__.py -> build/lib.linux-x86_64-3.6/av/codec
  creating build/lib.linux-x86_64-3.6/av/subtitles
  copying av/subtitles/__init__.py -> build/lib.linux-x86_64-3.6/av/subtitles
  creating build/lib.linux-x86_64-3.6/av/container
  copying av/container/__init__.py -> build/lib.linux-x86_64-3.6/av/container
  creating build/lib.linux-x86_64-3.6/av/data
  copying av/data/__init__.py -> build/lib.linux-x86_64-3.6/av/data
  creating build/lib.linux-x86_64-3.6/av/filter
  copying av/filter/__init__.py -> build/lib.linux-x86_64-3.6/av/filter
  creating build/lib.linux-x86_64-3.6/av/audio
  copying av/audio/__init__.py -> build/lib.linux-x86_64-3.6/av/audio
  running build_ext
  running reflect
  running config
  looking for avformat_open_input... found
  looking for pyav_function_should_not_exist... missing
  looking for av_calloc... found
  looking for av_frame_get_best_effort_timestamp... found
  looking for avformat_alloc_output_context2... found
  looking for avformat_close_input... found
  looking for avcodec_send_packet... found
  looking for AV_OPT_TYPE_INT...found
  looking for PYAV_ENUM_SHOULD_NOT_EXIST...missing
  looking for AV_OPT_TYPE_BOOL...found
  looking for AVStream.index... found
  looking for PyAV.struct_should_not_exist... missing
  looking for AVFrame.mb_type... missing
  writing build/temp.linux-x86_64-3.6/include/pyav/config.h
  running cythonize
  building 'av.stream' extension
  creating build/temp.linux-x86_64-3.6/src
  creating build/temp.linux-x86_64-3.6/src/av
  gcc -pthread -B /home/user/anaconda3/envs/my_env/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/user/anaconda3/envs/my_env/include/python3.6m -Iinclude -Ibuild/temp.linux-x86_64-3.6/include -I/usr/include/x86_64-linux-gnu -I/home/user/anaconda3/envs/my_env/include/python3.6m -Ibuild/temp.linux-x86_64-3.6/include -c src/av/stream.c -o build/temp.linux-x86_64-3.6/src/av/stream.o
  In file included from src/av/stream.c:636:
  include/libswresample/swresample.pyav.h:28:9: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     28 |     int avresample_version() { return -1; }
        |         ^~~~~~~~~~~~~~~~~~
  include/libswresample/swresample.pyav.h:29:17: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     29 |     const char* avresample_configuration() { return ""; }
        |                 ^~~~~~~~~~~~~~~~~~~~~~~~
  include/libswresample/swresample.pyav.h:30:17: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     30 |     const char* avresample_license() { return ""; }
        |                 ^~~~~~~~~~~~~~~~~~
  src/av/stream.c:639:10: fatal error: libavfilter/avfiltergraph.h: No such file or directory
    639 | #include "libavfilter/avfiltergraph.h"
        |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for av
  Running setup.py clean for av
Failed to build av

**Comment by edsun123** [comment]
had to change requirements.txt: for av==0.5.1

I also had to change versions for other packages as well. Let me know what is the requirement.txt currently used for ubuntu os

**Comment by siddy2000** [comment]
Did you figure out how to successfully install using ubuntu?
