### ISSUE TITLE
Running the program on tello edu 

### ISSUE THREAD

**Issue by edsun123** [aqeelanwar/DRLwithTL_real#19]
Hi,
I understand that this program was originally run on windows. I was wondering for anybody who ran on this on ubuntu, how were you able to connect to the Tello EDU and run the program? my ubuntu os was able to recognize the tello network but the video feed still remains blank. Perhaps there is additional packages needed to connect ubuntu to tello?

**Comment by ninannan2** [comment]
Tello EDU cannot generate the video file, so you cannot use this code with that drone.

**Comment by edsun123** [comment]
Have you tested on this on Tello EDU. Perhaps maybe there is a way to alter the code to work on the drone ... because they should have same firmware.

**Comment by edsun123** [comment]
Was able to resolve it by adding some libraries from tello and made skip_frame variable longer.

**Comment by ninannan2** [comment]
Have the same question.
