### ISSUE TITLE
Video stream is working but drone is not moving. 

### ISSUE THREAD

**Issue by edsun123** [aqeelanwar/DRLwithTL_real#21]
I'm currently able to get the stream working (video and depth map). However, in automatic mode the drone is not moving. Any insight in what is affecting the controls?

**Comment by naiveHobo** [comment]
Facing the same problem. @aqeelanwar any suggestions?

**Comment by ninannan2** [comment]
Press "Tab" to take off the drone; then press "M" to change the mode to automatic.

**Comment by edsun123** [comment]
I can confirm that this works.

**Comment by edsun123** [comment]
Did anybody get this particular error: "error while decoding MB 59 8, bytestream -14"? I am trying to pinpoint where the error is coming from.

**Comment by ninannan2** [comment]
I have some time this error. Couldn't fix it. If you find a solution let me know.

**Comment by edsun123** [comment]
I believe this is an error from ffmpeg that handles with video processing. Sometimes the video would jitter and that would result in the error.

I will close this issue but I will add onto this issue once I find a solution.
