### ISSUE TITLE
missing models

### ISSUE THREAD

**Issue by soldierofhell** [aqeelanwar/DRLwithTL_real#7]
Hi @aqeelanwar,

I cannot find anywhere models (checkpoints) that should be placed into Deepnet/models directory, like e.g. Deepnet/models/fcrn/NYU_FCRN.ckpt

Regards,

**Comment by aqeelanwar** [comment]
Hello,

The models can be found on the link below.
Download the entire folder named models and place it in the Deepnet folder.

**Comment by soldierofhell** [comment]
@aqeelanwar, thank you, but still don't see any link :)

**Comment by aqeelanwar** [comment]
My bad. Forgot to paste the link. Here it is.
https://drive.google.com/open?id=1YIs9wEqRbitFaRhZn9eRFQNnGulor_f4

Let me know if this works.

**Comment by soldierofhell** [comment]
@aqeelanwar, thanks, but still missing are trained weights for agent: "custom_load_path:           DeepNet/models/e2e/e2e" from the config.
Regards,

**Comment by edsun123** [comment]
Hi, thank you for this post. In the current version of the code, model_data_path inside heat_map.py is Deepnet/models/fcrn. I think the directory is misspelled and should be DeepNet/...
